version: "3.5"
services:
  redis:
    image: redis:alpine
    container_name: template_hono_bun_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory-policy noeviction
    restart: unless-stopped

volumes:
  redis-data:
