version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: template_hono_bun_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory-policy noeviction --requirepass ${REDIS_PASSWORD:-changeme}
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  redis-data:
